version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: workminder_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD:-root123}
      MYSQL_DATABASE: workminder_mvp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: